<?php

use App\Helpers\PersonBsnFake;

return [
    900244136 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900244148]],
            'kinderen' => [
                ['burgerservicenummer' => 900244161],
            ],
        ],
        'burgerservicenummer' => 900244136,
        'aNummer' => 2363230195,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(40),
        'naam' => [
            'geslachtsnaam' => 'Jansen',
            'voorletters' => 'P.',
            'voornamen' => 'Pieter',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'P. Jansen',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Lindelaan',
            'huisnummer' => 22,
            'postcode' => '1234AB',
            'woonplaats' => 'Utrecht',
            'nummeraanduidingIdentificatie' => '1234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Lindelaan',
            'adresregel1' => 'Lindelaan 22',
            'adresregel2' => '1234AB Utrecht',
        ],
    ],

    900244148 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900244136]],
            'kinderen' => [
                ['burgerservicenummer' => 900244161],
            ],
        ],
        'burgerservicenummer' => 900244148,
        'aNummer' => 2363230196,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(38),
        'naam' => [
            'geslachtsnaam' => 'De Vries',
            'voorletters' => 'M.',
            'voornamen' => 'Maria',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'M. Jansen - de Vries',
            'aanduidingNaamgebruik' => 'partner_eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Lindelaan',
            'huisnummer' => 22,
            'postcode' => '1234AB',
            'woonplaats' => 'Utrecht',
            'nummeraanduidingIdentificatie' => '1234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Lindelaan',
            'adresregel1' => 'Lindelaan 22',
            'adresregel2' => '1234AB Utrecht',
        ],
    ],

    900244161 => [
        '_embedded' => [],
        'burgerservicenummer' => 900244161,
        'aNummer' => 2363230197,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(10),
        'naam' => [
            'geslachtsnaam' => 'Jansen',
            'voorletters' => 'T.',
            'voornamen' => 'Tom',
            'voorvoegsel' => '',
        ],
        'verblijfplaats' => [
            'straat' => 'Lindelaan',
            'huisnummer' => 22,
            'postcode' => '1234AB',
            'woonplaats' => 'Utrecht',
            'nummeraanduidingIdentificatie' => '1234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Lindelaan',
            'adresregel1' => 'Lindelaan 22',
            'adresregel2' => '1234AB Utrecht',
        ],
    ],

    900244197 => [
        '_embedded' => [],
        'burgerservicenummer' => 900244197,
        'aNummer' => 2363230198,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(25),
        'naam' => [
            'geslachtsnaam' => 'Bakker',
            'voorletters' => 'L.',
            'voornamen' => 'Lisa',
            'voorvoegsel' => '',
        ],
        'verblijfplaats' => [
            'straat' => 'Stationsweg',
            'huisnummer' => 5,
            'postcode' => '5678CD',
            'woonplaats' => 'Eindhoven',
            'nummeraanduidingIdentificatie' => '2234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Stationsweg',
            'adresregel1' => 'Stationsweg 5',
            'adresregel2' => '5678CD Eindhoven',
        ],
    ],

    900203390 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900203407]],
        ],
        'burgerservicenummer' => 900203390,
        'aNummer' => 2363230199,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(65),
        'naam' => [
            'geslachtsnaam' => 'Mulder',
            'voorletters' => 'H.',
            'voornamen' => 'Henk',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'H. Mulder',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Dorpsstraat',
            'huisnummer' => 101,
            'postcode' => '9101EF',
            'woonplaats' => 'Dokkum',
            'nummeraanduidingIdentificatie' => '3234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Dorpsstraat',
            'adresregel1' => 'Dorpsstraat 101',
            'adresregel2' => '9101EF Dokkum',
        ],
    ],

    900203407 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900203390]],
        ],
        'burgerservicenummer' => 900203407,
        'aNummer' => 2363230200,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(63),
        'naam' => [
            'geslachtsnaam' => 'Mulder',
            'voorletters' => 'A.',
            'voornamen' => 'Annie',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'A. Mulder',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Dorpsstraat',
            'huisnummer' => 101,
            'postcode' => '9101EF',
            'woonplaats' => 'Dokkum',
            'nummeraanduidingIdentificatie' => '3234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Dorpsstraat',
            'adresregel1' => 'Dorpsstraat 101',
            'adresregel2' => '9101EF Dokkum',
        ],
    ],

    900158074 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900158086]],
            'kinderen' => [
                ['burgerservicenummer' => 999993847],
                ['burgerservicenummer' => 999992077],
                ['burgerservicenummer' => 999993483],
                ['burgerservicenummer' => 999990482],
                ['burgerservicenummer' => 999993653],
                ['burgerservicenummer' => 999995017],
                ['burgerservicenummer' => 999990408],
            ],
        ],
        'burgerservicenummer' => 900158074,
        'aNummer' => 2363230201,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(52),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'R.',
            'voornamen' => 'Robert',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'R. Smit',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    900158086 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900158074]],
            'kinderen' => [
                ['burgerservicenummer' => 999993847],
                ['burgerservicenummer' => 999992077],
                ['burgerservicenummer' => 999993483],
                ['burgerservicenummer' => 999990482],
                ['burgerservicenummer' => 999993653],
                ['burgerservicenummer' => 999995017],
                ['burgerservicenummer' => 999990408],
            ],
        ],
        'burgerservicenummer' => 900158086,
        'aNummer' => 2363230202,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(49),
        'naam' => [
            'geslachtsnaam' => 'Visser',
            'voorletters' => 'E.',
            'voornamen' => 'Elise',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'E. Smit - Visser',
            'aanduidingNaamgebruik' => 'partner_eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    999993847 => [
        '_embedded' => [],
        'burgerservicenummer' => 999993847,
        'aNummer' => 2363230203,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(24),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'L.',
            'voornamen' => 'Lotte',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    999992077 => [
        '_embedded' => [],
        'burgerservicenummer' => 999992077,
        'aNummer' => 2363230204,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(21),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'D.',
            'voornamen' => 'Daan',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    999993483 => [
        '_embedded' => [],
        'burgerservicenummer' => 999993483,
        'aNummer' => 2363230205,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(19),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'S.',
            'voornamen' => 'Sanne',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    999990482 => [
        '_embedded' => [],
        'burgerservicenummer' => 999990482,
        'aNummer' => 2363230206,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(17),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'T.',
            'voornamen' => 'Tim',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    999993653 => [
        '_embedded' => [],
        'burgerservicenummer' => 999993653,
        'aNummer' => 2363230208,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(12),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'M.',
            'voornamen' => 'Milan',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    999995017 => [
        '_embedded' => [],
        'burgerservicenummer' => 999995017,
        'aNummer' => 2363230209,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(8),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'F.',
            'voornamen' => 'Fenna',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],

    999990408 => [
        '_embedded' => [],
        'burgerservicenummer' => 999990408,
        'aNummer' => 2363230210,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(5),
        'naam' => [
            'geslachtsnaam' => 'Smit',
            'voorletters' => 'J.',
            'voornamen' => 'Jesse',
        ],
        'verblijfplaats' => [
            'straat' => 'Beukenlaan',
            'huisnummer' => 88,
            'postcode' => '3456GH',
            'woonplaats' => 'Amersfoort',
            'nummeraanduidingIdentificatie' => '4234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Beukenlaan',
            'adresregel1' => 'Beukenlaan 88',
            'adresregel2' => '3456GH Amersfoort',
        ],
    ],
    
    900285564 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 443588764]],
            'kinderen' => [
                ['burgerservicenummer' => 634387911],
                ['burgerservicenummer' => 766693521],
                ['burgerservicenummer' => 665843409],
            ],
        ],
        'burgerservicenummer' => 900285564,
        'aNummer' => 2363230211,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(55),
        'naam' => [
            'geslachtsnaam' => 'Van Dijk',
            'voorletters' => 'J.',
            'voornamen' => 'Jan',
            'voorvoegsel' => 'van',
            'aanschrijfwijze' => 'J. van Dijk',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Testlaan',
            'huisnummer' => 45,
            'postcode' => '1234ZZ',
            'woonplaats' => 'Mockdam',
            'nummeraanduidingIdentificatie' => '5234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Testlaan',
            'adresregel1' => 'Testlaan 45',
            'adresregel2' => '1234ZZ Mockdam',
        ],
    ],

    443588764 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900285564]],
            'kinderen' => [
                ['burgerservicenummer' => 634387911],
                ['burgerservicenummer' => 766693521],
                ['burgerservicenummer' => 665843409],
            ],
        ],
        'burgerservicenummer' => 443588764,
        'aNummer' => 2363230212,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(53),
        'naam' => [
            'geslachtsnaam' => 'Meijer',
            'voorletters' => 'A.',
            'voornamen' => 'Anita',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'A. van Dijk - Meijer',
            'aanduidingNaamgebruik' => 'partner_eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Testlaan',
            'huisnummer' => 45,
            'postcode' => '1234ZZ',
            'woonplaats' => 'Mockdam',
            'nummeraanduidingIdentificatie' => '5234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Testlaan',
            'adresregel1' => 'Testlaan 45',
            'adresregel2' => '1234ZZ Mockdam',
        ],
    ],

    634387911 => [
        '_embedded' => [],
        'burgerservicenummer' => 634387911,
        'aNummer' => 2363230213,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(3),
        'naam' => [
            'geslachtsnaam' => 'Van Dijk',
            'voorletters' => 'E.',
            'voornamen' => 'Emma',
        ],
        'verblijfplaats' => [
            'straat' => 'Testlaan',
            'huisnummer' => 45,
            'postcode' => '1234ZZ',
            'woonplaats' => 'Mockdam',
            'nummeraanduidingIdentificatie' => '5234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Testlaan',
            'adresregel1' => 'Testlaan 45',
            'adresregel2' => '1234ZZ Mockdam',
        ],
    ],

    766693521 => [
        '_embedded' => [],
        'burgerservicenummer' => 766693521,
        'aNummer' => 2363230214,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(15),
        'naam' => [
            'geslachtsnaam' => 'Van Dijk',
            'voorletters' => 'L.',
            'voornamen' => 'Lucas',
        ],
        'verblijfplaats' => [
            'straat' => 'Testlaan',
            'huisnummer' => 45,
            'postcode' => '1234ZZ',
            'woonplaats' => 'Mockdam',
            'nummeraanduidingIdentificatie' => '5234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Testlaan',
            'adresregel1' => 'Testlaan 45',
            'adresregel2' => '1234ZZ Mockdam',
        ],
    ],

    665843409 => [
        '_embedded' => [],
        'burgerservicenummer' => 665843409,
        'aNummer' => 2363230215,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(19),
        'naam' => [
            'geslachtsnaam' => 'Van Dijk',
            'voorletters' => 'M.',
            'voornamen' => 'Max',
        ],
        'verblijfplaats' => [
            'straat' => 'Testlaan',
            'huisnummer' => 45,
            'postcode' => '1234ZZ',
            'woonplaats' => 'Mockdam',
            'nummeraanduidingIdentificatie' => '5234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Testlaan',
            'adresregel1' => 'Testlaan 45',
            'adresregel2' => '1234ZZ Mockdam',
        ],
    ],

    900285576 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 231039803]],
        ],
        'burgerservicenummer' => 900285576,
        'aNummer' => 2363230216,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(34),
        'naam' => [
            'geslachtsnaam' => 'Bos',
            'voorletters' => 'K.',
            'voornamen' => 'Kim',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'K. Bos',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Voorbeeldstraat',
            'huisnummer' => 17,
            'postcode' => '2345YY',
            'woonplaats' => 'Demostad',
            'nummeraanduidingIdentificatie' => '6234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Voorbeeldstraat',
            'adresregel1' => 'Voorbeeldstraat 17',
            'adresregel2' => '2345YY Demostad',
        ],
    ],

    231039803 => [
        '_embedded' => [
            'partners' => [['burgerservicenummer' => 900285576]],
        ],
        'burgerservicenummer' => 231039803,
        'aNummer' => 2363230217,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(37),
        'naam' => [
            'geslachtsnaam' => 'Peters',
            'voorletters' => 'R.',
            'voornamen' => 'Ruben',
            'voorvoegsel' => '',
            'aanschrijfwijze' => 'R. Peters',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Voorbeeldstraat',
            'huisnummer' => 17,
            'postcode' => '2345YY',
            'woonplaats' => 'Demostad',
            'nummeraanduidingIdentificatie' => '6234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Voorbeeldstraat',
            'adresregel1' => 'Voorbeeldstraat 17',
            'adresregel2' => '2345YY Demostad',
        ],
    ],

    900285588 => [
        '_embedded' => [
            'kinderen' => [
                ['burgerservicenummer' => 678854774],
                ['burgerservicenummer' => 508707043],
            ],
        ],
        'burgerservicenummer' => 900285588,
        'aNummer' => 2363230218,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(51),
        'naam' => [
            'geslachtsnaam' => 'De Boer',
            'voorletters' => 'I.',
            'voornamen' => 'Ingrid',
            'voorvoegsel' => 'de',
            'aanschrijfwijze' => 'I. de Boer',
            'aanduidingNaamgebruik' => 'eigen',
        ],
        'verblijfplaats' => [
            'straat' => 'Molenstraat',
            'huisnummer' => 73,
            'postcode' => '3456XX',
            'woonplaats' => 'Fictieveen',
            'nummeraanduidingIdentificatie' => '7234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Molenstraat',
            'adresregel1' => 'Molenstraat 73',
            'adresregel2' => '3456XX Fictieveen',
        ],
    ],

    678854774 => [
        '_embedded' => [],
        'burgerservicenummer' => 678854774,
        'aNummer' => 2363230219,
        'geslachtsaanduiding' => 'vrouw',
        ...PersonBsnFake::makeBirthData(14),
        'naam' => [
            'geslachtsnaam' => 'De Boer',
            'voorletters' => 'N.',
            'voornamen' => 'Noa',
        ],
        'verblijfplaats' => [
            'straat' => 'Molenstraat',
            'huisnummer' => 73,
            'postcode' => '3456XX',
            'woonplaats' => 'Fictieveen',
            'nummeraanduidingIdentificatie' => '7234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Molenstraat',
            'adresregel1' => 'Molenstraat 73',
            'adresregel2' => '3456XX Fictieveen',
        ],
    ],

    508707043 => [
        '_embedded' => [],
        'burgerservicenummer' => 508707043,
        'aNummer' => 2363230220,
        'geslachtsaanduiding' => 'man',
        ...PersonBsnFake::makeBirthData(20),
        'naam' => [
            'geslachtsnaam' => 'De Boer',
            'voorletters' => 'T.',
            'voornamen' => 'Thijs',
        ],
        'verblijfplaats' => [
            'straat' => 'Havenstraat',
            'huisnummer' => 12,
            'postcode' => '7766AA',
            'woonplaats' => 'Proefburg',
            'nummeraanduidingIdentificatie' => '8234567890123456',
            'functieAdres' => 'woonadres',
            'korteNaam' => 'Havenstraat',
            'adresregel1' => 'Havenstraat 12',
            'adresregel2' => '7766AA Proefburg',
        ],
    ],
];
