component_depth: 1
languages:
- php
exclude:
- /app/Services/Forus/Session/Services/Data/AgentData.php
- /resources/lang/.*
- /config/.*
- /bootstrap/.*
- /routes/.*
- /database/.*
- /config/.*
- .*/_ide_helper\.php
