services:
  app:
    build:
      args:
        user: forus
        uid: 1000
      context: ./
      dockerfile: ./docker/docker-compose/php/Dockerfile
    image: forus-backend
    container_name: forus-backend-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - chrome-downloads:/var/www/storage/dusk-downloads
    ports:
      - "8000:80"
    depends_on:
      - forus-backend-db
    networks:
      - forus-network

  forus-backend-db:
    image: mysql:8.0
    container_name: forus-backend-db
    restart: unless-stopped
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/docker-compose/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - forus-network

  pma:
    depends_on:
      - forus-backend-db
    image: phpmyadmin/phpmyadmin
    profiles:
      - phpmyadmin
    container_name: forus-backend-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: forus-backend-db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - forus-network

  selenium:
    image: selenium/standalone-chrome
    shm_size: '1gb'
    profiles:
      - testing
    depends_on:
      - app
    container_name: forus-backend-selenium
    ports:
      - "4444:4444"
    networks:
      - forus-network
    volumes:
      - chrome-downloads:/home/seluser/Downloads

networks:
  forus-network:
    name: forus-network
    driver: bridge

volumes:
  chrome-downloads:
  mysql_data:
    driver: local
