name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - lexlog
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: env
    attributes:
      label: Environment
      description: Where did you met this bug?
      multiple: true
      options:
        - dev
        - staging
        - demo
        - prod
        - local
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Provide a version if you know it
      placeholder: v0.40.0