name: Create PR to develop after Master changes

on:
  push:
    branches:
      - 'master'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Create new branch
        run: |
          git checkout -b auto/master_to_develop_update master
          git push origin auto/master_to_develop_update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Merge changes from master'
          body: 'This pull request contains changes from the master branch.'
          branch: 'auto/master_to_develop_update'
          base: 'develop'
          #delete-branch: true
          labels: 'automated'
