name: Run browser tests

on:
  schedule:
    - cron: '00 3 * * *'
  pull_request:
    branches:
      - release/*
  workflow_dispatch:
    inputs:
      frontend_branch:
        description: 'Frontend branch name'
        required: false
        default: 'develop'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout forus-backend repo
        uses: actions/checkout@v3
        with:
          path: forus-backend

      - name: Copy .env.docker.dusk file to .env
        working-directory: forus-backend
        run: cp -n .env.docker.dusk .env

      - name: Run docker-compose up
        working-directory: forus-backend
        run: docker-compose --profile testing up -d

      - name: Crutch - set correct ownership of files in docker
        working-directory: forus-backend
        run: docker exec -u 0 forus-backend-app chown -R forus:forus /var/www/

      - name: Install dependencies
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "composer install"

      - name: Create database structure with artisan
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "composer dumpautoload && php artisan migrate"

      - name: Set app key
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "php artisan key:generate"

      - name: Run base seeders
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "php artisan db:seed"

      - name: Generate test data
        working-directory: forus-backend
        run: docker-compose exec -T app php artisan test-data:seed

      - name: "Set frontend branch value for manual and auto runs"
        run: |
          if [[ -z "${{ github.event.inputs.frontend_branch }}" ]]; then
            echo "Frontend branch param. is not set, setting default 'develop'"
            echo "FRONTEND_BRANCH=develop" >> $GITHUB_ENV
          else
            echo "Frontend branch param is set: ${{ github.event.inputs.frontend_branch }}"
            echo "FRONTEND_BRANCH=${{ github.event.inputs.frontend_branch }}" >> $GITHUB_ENV
          fi

      - name: Check out forus-frontend repo
        uses: actions/checkout@v3
        with:
          repository: teamforus/forus-frontend
          path: forus-frontend
          ref: ${{ env.FRONTEND_BRANCH }}

      - name: docker-compose up
        working-directory: forus-frontend
        run: mkdir -p dist && docker-compose up -d

      - name: Add forus-frontend to the backend network
        working-directory: forus-frontend
        run: |
          docker network connect --alias forus-frontend forus-backend_forus-network forus-frontend-app && \
          docker network inspect forus-backend_forus-network

      - name: Create qdt-env file and run npm install
        working-directory: forus-frontend
        run: docker-compose exec -T app sh -c "cd src && mv qdt-env.dusk.js qdt-env.js && npm install"

      - name: Run gulp init and gulp compile
        working-directory: forus-frontend
        run: docker-compose exec -T app sh -c "cd src && yes n | gulp init && gulp compile"

      - name: Run gulp server in background
        working-directory: forus-frontend
        run: docker-compose exec -T app sh -c "cd src && gulp serve &"

      - name: Debug - check docker images
        run: docker ps

      - name: Debug - print .env file
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "cat .env"

      - name: Debug - print qdt-env.js file
        working-directory: forus-frontend
        run: docker-compose exec -T app sh -c "cd src && cat qdt-env.js"

      - name: Debug - Check connection from front to front
        working-directory: forus-frontend
        run: docker-compose exec -T app sh -c "wget http://forus-frontend:3000"

      - name: Debug - Check connection from backend to frontend sponsor dashboard
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "wget http://forus-frontend:4000"

      - name: Debug - Check connection from backend to frontend provider dashboard
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "wget http://forus-frontend:5000"

      - name: Debug - Check connection from backend to frontend validator dashboard
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "wget http://forus-frontend:5500"

      - name: Install chrome driver
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "php artisan dusk:chrome"

      - name: --- RUN BROWSER TESTS ----
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "php artisan dusk --debug --verbose --testdox"

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Screenshots
          path: |
            forus-backend/tests/Browser/screenshots/*
            forus-backend/storage/logs/laravel.log
          retention-days: 5
