name: Run unit and feature tests

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout forus-backend repo
        uses: actions/checkout@v3
        with:
          path: forus-backend

      - name: Copy .env.docker.dusk file to .env
        working-directory: forus-backend
        run: cp -n .env.docker.dusk .env

      - name: Run docker-compose up
        working-directory: forus-backend
        run: docker-compose --profile testing up -d

      - name: Crutch - set correct ownership of files in docker
        working-directory: forus-backend
        run: docker exec -u 0 forus-backend-app chown -R forus:forus /var/www/

      - name: Install dependencies
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "composer install"

      - name: Create database structure with artisan
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "composer dumpautoload && php artisan migrate"

      - name: Set app key
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "php artisan key:generate"

      - name: Run base seeders
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "php artisan db:seed"

      - name: Generate test data
        working-directory: forus-backend
        run: docker-compose exec -T app php artisan test-data:seed

      - name: --- RUN UNIT TESTS ----
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "./vendor/bin/phpunit --debug --verbose --testdox tests/Unit/."

      - name: --- RUN FEATURE TESTS ----
        working-directory: forus-backend
        run: docker-compose exec -T app bash -c "./vendor/bin/phpunit --debug --verbose --testdox tests/Feature/."
